/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#004f50",
        "tertiary-fixed": "#dde3eb",
        "on-primary-fixed": "#001b3c",
        "primary-fixed": "#d6e3ff",
        "error": "#ba1a1a",
        "surface-container-low": "#eff4ff",
        "on-secondary-container": "#1a6d6e",
        "inverse-surface": "#223144",
        "secondary-fixed-dim": "#89d3d4",
        "on-tertiary-fixed": "#161c22",
        "on-surface": "#0d1c2e",
        "background": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "on-tertiary-fixed-variant": "#41474e",
        "primary-container": "#1a365d",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#86a0cd",
        "surface-container-highest": "#d4e4fc",
        "on-secondary-fixed": "#002020",
        "tertiary-fixed-dim": "#c1c7cf",
        "on-primary-fixed-variant": "#2d476f",
        "surface-container": "#e5eeff",
        "surface-tint": "#455f88",
        "surface": "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        "primary": "#002045",
        "surface-container-high": "#dce9ff",
        "primary-fixed-dim": "#adc7f7",
        "on-tertiary-container": "#989fa6",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "outline-variant": "#c4c6cf",
        "tertiary": "#1b2127",
        "surface-variant": "#d4e4fc",
        "inverse-primary": "#adc7f7",
        "secondary-fixed": "#a5eff0",
        "secondary-container": "#a2eded",
        "on-background": "#0d1c2e",
        "surface-dim": "#ccdbf4",
        "on-surface-variant": "#43474e",
        "on-error": "#ffffff",
        "tertiary-container": "#30363c",
        "on-primary": "#ffffff",
        "outline": "#74777f",
        "secondary": "#13696a"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "section-gap": "48px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "container-padding": "32px",
        "gutter": "24px",
        "stack-sm": "8px",
        "unit": "4px"
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "label-sm": ["JetBrains Mono"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "display-lg": ["Inter"],
        "label-md": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
